/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminSettings {
  'featuredProductIds' : Array<string>,
  'heroTitle' : string,
  'heroTagline' : string,
}
export interface Product {
  'id' : string,
  'features' : Array<string>,
  'imagePath' : string,
  'name' : string,
  'description' : string,
  'category' : string,
  'price' : bigint,
}
export interface Review {
  'id' : bigint,
  'authorName' : string,
  'reviewText' : string,
  'productId' : string,
  'timestamp' : bigint,
  'rating' : bigint,
}
export interface _SERVICE {
  'addReview' : ActorMethod<[string, bigint, string, string], bigint>,
  'adminLogin' : ActorMethod<[string], boolean>,
  'deleteReview' : ActorMethod<[bigint, string], boolean>,
  'getAdminSettings' : ActorMethod<[], AdminSettings>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getProductById' : ActorMethod<[string], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getReviewsByProduct' : ActorMethod<[string], Array<Review>>,
  'setFeaturedProducts' : ActorMethod<[Array<string>], undefined>,
  'updateHeroText' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];