/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminSettings {
  'currentlyCrafting' : string,
  'whatsappSubscribers' : Array<WhatsappSubscriber>,
  'soldOutProductIds' : Array<string>,
  'bundles' : Array<Bundle>,
  'featuredProductIds' : Array<string>,
  'productTimers' : Array<ProductTimer>,
  'pressEntries' : Array<PressEntry>,
  'heroTitle' : string,
  'heroTagline' : string,
}
export interface BackInStockSubscription {
  'subscribedAt' : bigint,
  'email' : string,
}
export interface Bundle {
  'id' : string,
  'productIds' : Array<string>,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'badge' : string,
  'price' : bigint,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface PressEntry {
  'id' : string,
  'url' : string,
  'outlet' : string,
  'title' : string,
  'date' : string,
}
export interface Product {
  'id' : string,
  'features' : Array<string>,
  'imagePath' : string,
  'name' : string,
  'description' : string,
  'category' : string,
  'price' : bigint,
}
export interface ProductImage { 'productId' : string, 'imageUrl' : string }
export interface ProductTimer {
  'productId' : string,
  'caption' : string,
  'endTimestamp' : bigint,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface Review {
  'id' : bigint,
  'authorName' : string,
  'reviewText' : string,
  'productId' : string,
  'timestamp' : bigint,
  'rating' : bigint,
}
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface WhatsappSubscriber {
  'id' : string,
  'subscribedAt' : bigint,
  'name' : string,
  'phone' : string,
}
export interface _SERVICE {
  'addReview' : ActorMethod<[string, bigint, string, string], bigint>,
  'adminLogin' : ActorMethod<[string], boolean>,
  'deleteReview' : ActorMethod<[bigint, string], boolean>,
  'execute' : ActorMethod<[string], Result>,
  'getAdminSettings' : ActorMethod<[], AdminSettings>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getApiDoc' : ActorMethod<[], string>,
  'getBackInStockSubscribers' : ActorMethod<
    [string],
    Array<BackInStockSubscription>
  >,
  'getProductById' : ActorMethod<[string], [] | [Product]>,
  'getProductImage' : ActorMethod<[string], [] | [string]>,
  'getProductImages' : ActorMethod<[], Array<ProductImage>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getReviewsByProduct' : ActorMethod<[string], Array<Review>>,
  'notifyBackInStock' : ActorMethod<[string, string], undefined>,
  'schema' : ActorMethod<[], string>,
  'setBundles' : ActorMethod<[Array<Bundle>], undefined>,
  'setCurrentlyCrafting' : ActorMethod<[string], undefined>,
  'setFeaturedProducts' : ActorMethod<[Array<string>], undefined>,
  'setPressEntries' : ActorMethod<[Array<PressEntry>], undefined>,
  'setProductImage' : ActorMethod<[string, string], undefined>,
  'setProductTimers' : ActorMethod<[Array<ProductTimer>], undefined>,
  'setSoldOutProducts' : ActorMethod<[Array<string>], undefined>,
  'setWhatsappSubscribers' : ActorMethod<
    [Array<WhatsappSubscriber>],
    undefined
  >,
  'subscribeBackInStock' : ActorMethod<[string, string], undefined>,
  'updateHeroText' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];