/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const WhatsappSubscriber = IDL.Record({
  'id' : IDL.Text,
  'subscribedAt' : IDL.Int,
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const Bundle = IDL.Record({
  'id' : IDL.Text,
  'productIds' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'badge' : IDL.Text,
  'price' : IDL.Nat,
});
export const ProductTimer = IDL.Record({
  'productId' : IDL.Text,
  'caption' : IDL.Text,
  'endTimestamp' : IDL.Int,
});
export const PressEntry = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'outlet' : IDL.Text,
  'title' : IDL.Text,
  'date' : IDL.Text,
});
export const AdminSettings = IDL.Record({
  'currentlyCrafting' : IDL.Text,
  'whatsappSubscribers' : IDL.Vec(WhatsappSubscriber),
  'soldOutProductIds' : IDL.Vec(IDL.Text),
  'bundles' : IDL.Vec(Bundle),
  'featuredProductIds' : IDL.Vec(IDL.Text),
  'productTimers' : IDL.Vec(ProductTimer),
  'pressEntries' : IDL.Vec(PressEntry),
  'heroTitle' : IDL.Text,
  'heroTagline' : IDL.Text,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'authorName' : IDL.Text,
  'reviewText' : IDL.Text,
  'productId' : IDL.Text,
  'timestamp' : IDL.Int,
  'rating' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'imagePath' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const ProductImage = IDL.Record({
  'productId' : IDL.Text,
  'imageUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'addReview' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteReview' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getAdminSettings' : IDL.Func([], [AdminSettings], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getProductById' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getProductImage' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getProductImages' : IDL.Func([], [IDL.Vec(ProductImage)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getReviewsByProduct' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setBundles' : IDL.Func([IDL.Vec(Bundle)], [], []),
  'setCurrentlyCrafting' : IDL.Func([IDL.Text], [], []),
  'setFeaturedProducts' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'setPressEntries' : IDL.Func([IDL.Vec(PressEntry)], [], []),
  'setProductImage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setProductTimers' : IDL.Func([IDL.Vec(ProductTimer)], [], []),
  'setSoldOutProducts' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'setWhatsappSubscribers' : IDL.Func([IDL.Vec(WhatsappSubscriber)], [], []),
  'updateHeroText' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const WhatsappSubscriber = IDL.Record({
    'id' : IDL.Text,
    'subscribedAt' : IDL.Int,
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Bundle = IDL.Record({
    'id' : IDL.Text,
    'productIds' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'badge' : IDL.Text,
    'price' : IDL.Nat,
  });
  const ProductTimer = IDL.Record({
    'productId' : IDL.Text,
    'caption' : IDL.Text,
    'endTimestamp' : IDL.Int,
  });
  const PressEntry = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'outlet' : IDL.Text,
    'title' : IDL.Text,
    'date' : IDL.Text,
  });
  const AdminSettings = IDL.Record({
    'currentlyCrafting' : IDL.Text,
    'whatsappSubscribers' : IDL.Vec(WhatsappSubscriber),
    'soldOutProductIds' : IDL.Vec(IDL.Text),
    'bundles' : IDL.Vec(Bundle),
    'featuredProductIds' : IDL.Vec(IDL.Text),
    'productTimers' : IDL.Vec(ProductTimer),
    'pressEntries' : IDL.Vec(PressEntry),
    'heroTitle' : IDL.Text,
    'heroTagline' : IDL.Text,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'authorName' : IDL.Text,
    'reviewText' : IDL.Text,
    'productId' : IDL.Text,
    'timestamp' : IDL.Int,
    'rating' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'imagePath' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const ProductImage = IDL.Record({
    'productId' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'addReview' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteReview' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getAdminSettings' : IDL.Func([], [AdminSettings], ['query']),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getProductById' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getProductImage' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getProductImages' : IDL.Func([], [IDL.Vec(ProductImage)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getReviewsByProduct' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setBundles' : IDL.Func([IDL.Vec(Bundle)], [], []),
    'setCurrentlyCrafting' : IDL.Func([IDL.Text], [], []),
    'setFeaturedProducts' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'setPressEntries' : IDL.Func([IDL.Vec(PressEntry)], [], []),
    'setProductImage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setProductTimers' : IDL.Func([IDL.Vec(ProductTimer)], [], []),
    'setSoldOutProducts' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'setWhatsappSubscribers' : IDL.Func([IDL.Vec(WhatsappSubscriber)], [], []),
    'updateHeroText' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };