/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AdminSettings = IDL.Record({
  'featuredProductIds' : IDL.Vec(IDL.Text),
  'heroTitle' : IDL.Text,
  'heroTagline' : IDL.Text,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'authorName' : IDL.Text,
  'reviewText' : IDL.Text,
  'productId' : IDL.Text,
  'timestamp' : IDL.Int,
  'rating' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'imagePath' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addReview' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteReview' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'getAdminSettings' : IDL.Func([], [AdminSettings], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getProductById' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getReviewsByProduct' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'setFeaturedProducts' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'updateHeroText' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AdminSettings = IDL.Record({
    'featuredProductIds' : IDL.Vec(IDL.Text),
    'heroTitle' : IDL.Text,
    'heroTagline' : IDL.Text,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'authorName' : IDL.Text,
    'reviewText' : IDL.Text,
    'productId' : IDL.Text,
    'timestamp' : IDL.Int,
    'rating' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'imagePath' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'addReview' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteReview' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'getAdminSettings' : IDL.Func([], [AdminSettings], ['query']),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getProductById' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getReviewsByProduct' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
    'setFeaturedProducts' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'updateHeroText' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };